<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Dmb.Crm.Api</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.11" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="AutoMapper" Version="14.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\DMB.CRM.DATA\DMB.CRM.DATA.csproj" />
    <ProjectReference Include="..\DMB.CRM.MODEL\DMB.CRM.MODEL.csproj" />
    <ProjectReference Include="..\DMB.CRM.Service\DMB.CRM.Service.csproj" />
  </ItemGroup>
</Project>
